name: Duels
authors: ["Jack Noordhuis"]
version: 0.0.2_ALPHA
description: Conflict's duels plugin
main: duels\Main
load: POSTWORLD
depend:
  - Components
api: ["2.0.0"]

commands:
  duel:
    aliases: ["battle", "fight", "1v1"]
    description: "Starts a duel with the specified player"
  hub:
    aliases: ["spawn", "lobby", "leave", "quit"]
    description: "Leave your current duel and teleport to spawn"
  party:
    aliases: ["p"]
    description: "Manage your party"